[[agents]]
id = 'bob'
name = 'Bob'
keystore_file = 'bob.key'
public_address = 'HcSCJnbgD9t4E3m4feNmVzOfwEwr84x4rW6OI87s4c4i5Qh3vY663b3NCxeSjca'
test_agent = true

[[dnas]]
file = 'dist/1_hello_holo.dna.json'
hash = 'QmQejrWBhrXrXwqHhWwbBZik7tF3bPqDsKmMpjc5Jn5EYE'
# hash = 'QmS4zPxp13YneR43Wk15UEJxRYv2JjJhCMpVK4zpRtjGtz'
id = 'hc-run-dna'

[[instances]]
agent = 'bob'
dna = 'hc-run-dna'
id = 'test-instance'

[instances.storage]
type = "memory"

[[interfaces]]
admin = true
id = 'http-interface'

[[interfaces.instances]]
id = 'test-instance'

[interfaces.driver]
port = 3402
type = 'http'

[network]
type = 'sim2h'
sim2h_url = 'wss://sim2h.holochain.org:9000'
